osadetsvitalii__exam
viktor-beet-root/exam pull request #7
Opened 2020-12-15 16:18 UTC by vitaliiosadets

2020-12-18 12:57 UTC, viktor-beet-root requested changes

2020-12-18 12:57 UTC, viktor-beet-root commented on osadets_vitalii/css/style.css.map
> +{"version":3,"sources":["style.css","../src/_vars.scss","../src/normalize.scss","../src/_mixin.scss","../src/_fonts.scss","../src/_page.scss","../src/_container.scss","../src/_button.scss","../src/_h
мапы при сдаче должны быть выключены

2020-12-18 12:57 UTC, viktor-beet-root commented on osadets_vitalii/index.html
> +    <section class="home">
нет зедера футера и тега мэйн

2020-12-18 12:57 UTC, viktor-beet-root commented on osadets_vitalii/src/_feedback.scss
> +        @media screen and (max-width: 800px){
брейк поинты должны быть в переменных и ты трохи не стандартные значения используешь

2020-12-18 12:57 UTC, viktor-beet-root commented on osadets_vitalii/src/_search.scss
> +
лишние пустоты поубирай

2020-12-22 21:26 UTC, viktor-beet-root commented on .gitignore
> +/**/osadets_vitalii/css/style.css.map
этот таки файл не нужно было трогать, для этого есть локальный исключения погугли

2020-12-22 21:26 UTC, viktor-beet-root commented on osadets_vitalii/index.html
> +                    <span class="scroll__line"></span></a>
этого пустого тега могло и не быть, у тебя есть псевдоклассы

2020-12-22 21:26 UTC, viktor-beet-root commented on osadets_vitalii/src/_menu.scss
> +			height: 20px;
код отформатирован не верно у тебя не пробелы, а символ табуляции
нужно исправить все файлы

2021-02-14 00:38 UTC, viktor-beet-root requested changes

2021-02-14 00:38 UTC, viktor-beet-root commented on osadets_vitalii/index.html
> +                    <span class="scroll__line"></span></a>
я все еще наблюдаю пустой тег этого тут не должно быть

2021-02-14 00:38 UTC, viktor-beet-root commented on osadets_vitalii/src/_loft.scss
> +		font-size: 20px;
код отформатирован не верно тут табуляции, а не пробелы

2021-02-21 17:04 UTC, viktor-beet-root requested changes

2021-02-21 17:04 UTC, viktor-beet-root commented on osadets_vitalii/index.html
> +				<div class="home__header">
тут все еще отступы сделаны табуляцией должны быть пробелы
и во всех остальных файлах так же

2021-02-21 17:04 UTC, viktor-beet-root commented on osadets_vitalii/css/style.css
> +@charset "UTF-8";
этот файл должен быть минифицирован

2021-02-27 18:18 UTC, vitaliiosadets commented on osadets_vitalii/css/style.css
> +@charset "UTF-8";
Это ведь первый экзамен на препроцессоре.

2021-03-01 20:07 UTC, merged